name: Publish Docker Image and Node Module
on:
  push:
    branches:
      - "main"
jobs:
  npm_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com/yazilim-vip"
      - run: |
          yarn install
          yarn build
          yarn package:linux
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@master
        with:
          name: bundle
          path: bundle

