name: Publish Docker Image and Node Module
on:
  push:
    branches:
      - "main"
  release:
    types:
      - "published"
jobs:
  npm_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"
        registry-url: "https://npm.pkg.github.com/yazilim-vip"
    - run: | 
        yarn install
        yarn build
        yarn publish 
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@master
      with:
        name: bin
        path: bin

  # docker_image_publish:
  #   needs: [ npm_publish ]
  #   name: Push Docker image to Docker Hub
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v2
  #     - uses: actions/download-artifact@master
  #       with:
  #         name: bin
  #         path: bin
  #     - name: Push to Docker Hub
  #       uses: docker/build-push-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #         repository: yazilimvip/howto-script
  #         tag_with_ref: true